export {
  WEATHER_ICON_MAP,
  DRY_NORMAL_ICON_PATH,
  DRY_SUNRISE_ICON_PATH,
  DRY_SUNSET_ICON_PATH,
  SUNRISE_SUNSET_WINDOW_MS,
  inferWetSeverity,
  computeHeatIndexC,
  resolveHeatSeverity,
  resolveIntensityLabel,
  resolveIsNight,
  resolveThunderFlag,
  resolveDrySeasonNightIcon,
  resolveDrySeasonPhaseIcon,
  resolveWetSeasonIconPath,
  buildAutoDescription,
} from "../../api/src/utils/weather";
